language: node_js
node_js:
  - "0.11"
env:
  global:
    - secure: mGOLbQFXBVj3sstbDgMJcIUPKWeXwkJaFoqP+zDgaiIkFdOUTubHWLMhhXr03XSIylQCUIM2DMe6GBdt0or5CqcmeKP3xxeWRp9CcQ6Pw6ARIJvsa4zSlDt14lDl20/Gnz2jxa2XYVoV8m1NJfIYYenm7p9PbvkuoKHK2+4XFrI=
    - secure: XISpc1iUkQa6HvLp1mWannkw2znpjzGyEN2tFlacgf8vxC1lsrWe0ciDl/fextu6H0IRZA5btTqqsJUbuPOMPsuDq0JM07FMgOzNzcZN6nizizCujbN9BxiyJX5q3WR5rJ2eNBN/Abq6bRN9Tilqsd4K/G4MhX6a09k1MAbpEAk=
before_script: npm install -g gulp karma-cli