language: node_js
node_js:
  - "0.11"
env:
  global:
    - secure: ugbka1Kft78ycSC8ci3nBdYxOZ+VEiHYm52pHeaJ7ju7WiJ6A9CY/FhGvfFUi8LHm5CzLQhG9JP3g9X5O1S/vt52lJSgSTV95qw1USiRI6jEIi/fw5MffG6eM7lmhqH9UWLQlcIiwYV6M+yTdQnBRVEaB6/fyerC2A9kPpCIKL4=
    - secure: bL80L3rjVJSE2aF1CouhpRPZt/9Ke6Mv9Fv5JWxVyFmvxGxHpVVSnrAwHJXeBwpuGiComkJyUvPQ0Bs8ksFXsETkD6EFowySow5KuDnkkK1CMHqFnjQbQBzzpzKr35CILVNyr2Cikqz9LpH8S1oAbk0Vlotw3N4+ADMvYS9dZNo=
before_script: npm install -g gulp karma-cli